# Generated by Django 5.1.2 on 2024-10-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0002_rename_date_created_clinicalnote_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='next_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
    ]
